### ISSUE TITLE
create roles api, controller and dao

### ISSUE THREAD

**Issue by letterix** [Softhouse/xyz-cv-api#9]
need to create a chain for handling creation and removal of roles. The roles have the simple format of: 

```
{
    name: roleName
}
```

**Comment by Tobbe** [comment]
Is it an object just to work with DREAMS? Because from the sound of it I think normally a simple text string would work

**Comment by letterix** [comment]
Yes it's an object to work with DREAMS, however, i use it simply to make it possible to add roles dynamically. Is there another way or do we want the roles to be truly static?
